name = "bss-support-chat"
main = "worker.js"
compatibility_date = "2024-12-01"


# Add your D1 database IDs before deploying.
[[d1_databases]]
binding = "DB"
database_name = "bss_support_chat"
database_id = "5918dbcd-65eb-4352-b196-b167f5571a86"
preview_database_id = "0ad6de03-5ba0-4132-bb62-f34718220f29"

[vars]
ALLOWED_ORIGINS = "*"
